language: python

python:
  - 3.6
  - 3.7
  - 3.8

install:
  - pip install .
  - pip install flake8 flake8-docstrings pytest pytest-cov codecov

script:
  - flake8
  - pytest -v --cov-config=.coveragerc --cov=./peridynamics

after_success:
  - codecov

jobs:
  include:
    - python: 3.7
      install:
        - pip install .
        - pip install sphinx
      script: sphinx-build -W -b html docs build
